# APL to NumPy Translation
Examples taken from the "Langauge Overview" Cheat Sheet available on https://tryapl.org/

-----------------------------

In [1]:
import numpy as np

In [2]:
#------------------------
# Example Cell Structure
#------------------------

#       {APL Code Example}
# {APL Output}

numpy_code_example = "Numpy Code Input"
numpy_code_example = numpy_code_example.replace("Input", "Output")
numpy_code_example

'Numpy Code Output'

----------------------------
## Mathematics
----------------------------

## Plus (+)

### Monadic - Conjugate

In [3]:
#       + 1.2 0j4 ¯5j¯6
# 1.2 0J¯4 ¯5J6

np.vectorize(complex.conjugate)(
    np.array([1.2, complex(0, 4), complex(-5, -6)])
)

array([ 1.2-0.j,  0. -4.j, -5. +6.j])

### Dyadic - Plus

In [4]:
#       1 2 3 4 + 10
# 11 12 13 14

np.array([1, 2, 3, 4]) + 10

array([11, 12, 13, 14])

In [5]:
#       1 2 3 + 2 ¯4 1
# 3 ¯2 4

np.array([1, 2, 3]) + np.array([2, -4, 1])

array([ 3, -2,  4])

In [6]:
#       +/ 1 2 3
# 6

np.array([1, 2, 3]).sum()

6

## Minus (-)

### Monadic - Negate

In [7]:
#       - 3.2 ¯7 0
# ¯3.2 7 0

np.negative(
    [3.2, -7, 0]
)

array([-3.2,  7. , -0. ])

### Dyadic - Minus

In [8]:
#       3 7 9 - 5
# ¯2 2 4

np.array([3, 7, 9]) - 5

array([-2,  2,  4])

In [9]:
#       5 1 4 - 2 3 4
# 3 ¯2 0

np.array([5, 1, 4]) - np.array([2, 3, 4])

array([ 3, -2,  0])

## Times (×)

### Monadic - Direction

In [10]:
#       × 3.1 ¯2 0 3j4
# 1 ¯1 0 0.6J0.8
#
# Left off the complex # in python

np.sign(
    [3.1, -2, 0]
)

array([ 1., -1.,  0.])

### Dyadic - Times

In [11]:
#       2 ¯3 4.5 × ¯3 ¯4 2
# ¯6 12 9

np.array([2, -3, 4.5]) * np.array([-3, -4, 2])

array([-6., 12.,  9.])

In [12]:
#       3 1 4 × 10
# 30 10 40

np.array([3, 1, 4]) * 10

array([30, 10, 40])

In [13]:
#       ×/ 2 3 4
# 24

np.multiply.reduce(
    [2, 3, 4]
)

24

## Divide (÷)

### Monadic - Reciprocal

In [14]:
#       ÷ 1 2 3
# 1 0.5 0.333333

np.reciprocal(
    [1.0, 2.0, 3.0]  # will not work with integers here, 
)

array([1.        , 0.5       , 0.33333333])

### Dyadic - Divide

In [15]:
#       1 2 3 ÷ 4 5 7
# 0.25 0.4 0.428571

np.array([1, 2, 3]) / np.array([4, 5, 7])

array([0.25      , 0.4       , 0.42857143])

In [16]:
#       10 ÷ ¯2 0.5
# ¯5 20

10 / np.array([-2, 0.5])

array([-5., 20.])

## Upstile (⌈)

### Monadic - Ceiling (Round Up)

In [17]:
#       ⌈ 3.4 ¯3.4 3 0
# 4 ¯3 3 0

np.ceil(
    [3.4, -3.4, 3, 0]
)

array([ 4., -3.,  3.,  0.])

### Dyadic - Maximum

In [18]:
#       1.1 ¯2 ⌈ 8.1 ¯3.4
# 8.1 ¯2

np.fmax(
    [1.1, -2], [8.1, -3.4]
)

array([ 8.1, -2. ])

In [19]:
#       ⌈/ 3 1 4 1
# 4

np.array([3, 1, 4, 1]).max()

4

## Downstile (⌊)

### Monadic - Floor (Round Down)

In [20]:
#       ⌊ 3.4 ¯3.4 3 0
# 3 ¯4 3 0

np.floor(
    [3.4, -3.4, 3, 0]
)

array([ 3., -4.,  3.,  0.])

### Dyadic - Minimum

In [21]:
#       1.1 ¯2 ⌊ 8.1 ¯3.4
# 1.1 ¯3.4

np.fmin(
    [1.1, -2], [8.1, -3.4]
)

array([ 1.1, -3.4])

In [22]:
#       ⌊/ 3 1 4 1
# 1

np.array([3, 1, 4, 1]).min()

1

## Star (*)

### Monadic - Exponential

In [23]:
#       * 0 1 2
# 1 2.71828 7.38906

np.exp(
    [0, 1, 2]
)

array([1.        , 2.71828183, 7.3890561 ])

### Dyadic - Power

In [24]:
#      49 5 ¯4 * 0.5 2 0.5
# 7 25 0J2
#
# Left off the complex # in python

np.array([49, 5]) ** np.array([0.5, 2])

array([ 7., 25.])

## Exclamation Mark (!)

### Monadic - Factorial

In [25]:
#       ! 3 9 ¯0.11
# 6 362880 1.07683
#
# Left off the non-integral value # in python

import math

np.vectorize(math.factorial)(
    [3, 9]
)

array([     6, 362880])

### Dyadic - Binomial

In [26]:
#       2 1 3 ! 3 10 ¯0.11
# 3 10 ¯0.0429385
#
# Left off the non-integral value # in python

from itertools import combinations

def unique_groups(alpha, omega):
    return len(
               list(
                   combinations(
                       range(omega), 
                       alpha
                   )
               )
           )

np.vectorize(unique_groups)(
    [2, 1, 2], [3, 10, 6]
)

array([ 3, 10, 15])

## Stile (|)

### Monadic - Magnitude (Absolute value)

In [27]:
#       | 2.3 ¯4 0 3j4
# 2.3 4 0 5

np.absolute(
    [2.3, -4, 0, complex(3, 4)]
)

array([2.3, 4. , 0. , 5. ])

### Dyadic - Residue (Remainder/Modulus)

In [28]:
#       2 10 ¯2.5 | 7 ¯13 8
# 1 7 ¯2

np.array([7, -13, 8]) % np.array([2, 10, -2.5])

array([ 1.,  7., -2.])

## Log (⍟)

### Monadic - Natural Logarithm

In [29]:
#       ⍟ 1 2 3 2.7182818285
# 0 0.693147 1.09861 1

np.log(
    [1, 2, 3, 2.7182818285]
)

array([0.        , 0.69314718, 1.09861229, 1.        ])

### Dyadic - Logarithm

In [30]:
# Based on: https://en.wikipedia.org/wiki/Logarithm#Change_of_base

#       2 10 ⍟ 32 1000
# 5 3

def log_base_change(base, number):
    return np.log(number) / np.log(base)

np.vectorize(log_base_change)(
    [2, 10], [32, 1000]
)

array([5., 3.])

## Circle (○)

### Monadic - Pi Times

In [31]:
#       ○ 0 1 2
# 0 3.14159 6.28319

print("Not Implemented Yet")

Not Implemented Yet


### Dyadic - Circular Functions (Trig)
          Note: Angles are in radians 
                radians ← ○ degrees ÷ 180

In [32]:
# APL has the 25 "circular" functions below built into this ○ function 
# and able to be called by the number passed into alpha 
# 
#       1 ○ 0 1.5707963 3.1415927
# 0 1 ¯4.64102E¯8
# 
#  ⍺   ⍺ ○ ⍵         ⍺   ⍺ ○ ⍵    
#                    0   (1-⍵*2)*0.5
# ¯1   Arcsin ⍵      1   Sine ⍵
# ¯2   Arccos ⍵      2   Cosine ⍵
# ¯3   Arctan ⍵      3   Tangent ⍵
# ¯4   (¯1+⍵*2)*0.5  4   (1+⍵*2)*0.5
# ¯5   Arcsinh ⍵     5   Sinh ⍵
# ¯6   Arccosh ⍵     6   Cosh ⍵
# ¯7   Arctanh ⍵     7   Tanh ⍵
# ¯8   -8○⍵          8   (-1+⍵*2)*0.5
# ¯9   ⍵             9   real part of ⍵
# ¯10  +⍵           10   |⍵
# ¯11  ⍵×0J1        11   imaginary part of ⍵
# ¯12  *⍵×0J1       12   phase of ⍵

circle_dict = {
    0: lambda x: (1-x**2)**0.5,
    1: np.sin,
    2: np.cos,
    3: np.tan,
    4: lambda x: (1+x**2)**0.5,
    5: np.sinh,
    6: np.cosh,
    7: np.tanh,
    8: lambda x: (-1*(1+x**2))**0.5,
    9: np.real,
    10: np.absolute,
    11: np.imag,
    12: "Not Implemented Yet",
    
    -1: np.arcsin,
    -2: np.arccos,
    -3: np.arctan,
    -4: lambda x: (-1+x**2)**0.5,
    -5: np.arcsinh,
    -6: np.arccosh,
    -7: np.arctanh,
    -8: lambda x: complex(0, ((1+x**2)*-1)**0.5),
    -9: lambda x: x,
    -10: complex.conjugate,
    -11: lambda x: complex(0, x),
    -12: "Not Implemented Yet",
}

## Domino (⌹)

### Monadic - Matrix Inverse

In [33]:
#       mat
# 1 2
# 3 4
#       ⌹ mat
# ¯2    1
#  1.5 ¯0.5

mat = np.matrix('1 2; 3 4')
mat.I

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

### Dyadic - Matrix Divide

In [34]:
#       5 6 ⌹ mat
# ¯4 4.5

mat = np.matrix('1 2; 3 4')
vector = np.array([5, 6])
print("Not Implemented Yet")

Not Implemented Yet


## Up Tack (⊥)

### Dyadic - Decode

In [35]:
#       2 ⊥ 1 1 0 1   ⍝ binary decode
# 13

arr = np.array([1, 1, 0, 1])
arr_str = "".join((str(i) for i in arr))

int(arr_str, 2)

13

In [36]:
# ⍝ mixed radix: conversion of hours,
# ⍝ minutes and seconds to seconds:

#       24 60 60 ⊥ 2 46 40
# 10000

def decode_mixed_radix(alpha, omega):
    assert len(alpha) == len(omega)
    result = 0
    
    for i in range(len(alpha)):        
        temp = omega[i]
        
        for j in range(i+1, len(alpha)):
            temp *= alpha[j]
            
        result += temp
        
    return result

decode_mixed_radix(
    np.array([24, 60, 60]),
    np.array([2, 46, 40]),
)

10000

## Down Tack (⊤)

### Dyadic - Encode

In [37]:
#       2 2 2 2 ⊤ 5 7 12   ⍝ binary encode
# 0 0 1
# 1 1 1
# 0 1 0
# 1 1 0

print("Not Implemented Yet")

Not Implemented Yet


In [38]:
# ⍝ mixed radix: encode of 10000 seconds
# ⍝ to hours, minutes and seconds:

#       24 60 60 ⊤ 10000
# 2 46 40

def encode_mixed_radix(alpha, omega):
    alpha = alpha[::-1]
    result = []
    
    for a in alpha:
        omega, remainder = divmod(omega, a)
        result.append(remainder)
    
    return np.array(result[::-1])
    

encode_mixed_radix([24, 60, 60], 10000)

array([ 2, 46, 40])

## Question Mark (?)

### Monadic - Roll

In [39]:
#       ? 6 6 6 6 6
# 4 3 6 3 5

import random

# APL will never return zero as a choice here
roll = lambda x: random.choice(range(1, x))
np.vectorize(roll)([6, 6, 6, 6, 6])

array([2, 5, 3, 1, 5])

In [40]:
#       ? 0 0
# 0.260561 0.929928

# APL will never return zero as a choice here
roll_zero = lambda x: random.random()
np.vectorize(roll_zero)([0, 0])

array([0.99966387, 0.69800911])

### Dyadic - Deal

In [41]:
#       13 ? 52
# 36 31 44 11 27 42 13 8 2 33 19 34 6

def sample(alpha, omega):
    return random.sample(range(omega), alpha)

np.array(
    sample(13, 52)
)

array([ 4, 16, 44, 46, 48, 45, 42, 51, 49,  9,  2,  0, 29])

-------------------------
## Logic and Comparison
-------------------------

## Tilde (~)

### Monadic - NOT

In [42]:
#       ~ 0 1 0 1
# 1 0 1 0

def logic_not(omega):
    return [
        int(np.logical_not(o)) 
        for o in omega
    ]
        
logic_not(
    [0, 1, 0, 1]
)

[1, 0, 1, 0]

### Dyadic - Without

In [43]:
#       3 1 4 1 5 ~ 5 1
# 3 4

def without(alpha, omega):
    return [
        a for a in alpha 
        if a not in omega
    ]

np.array(
    without(
        [3, 1, 4, 1, 5], [5, 1]
    )
)

array([3, 4])

In [44]:
#       'aa' 'bb' 'cc' 'bb'  ~ 'bb' 'xx'
# ┌──┬──┐
# │aa│cc│
# └──┴──┘

np.array(
    without(
        ['aa', 'bb', 'cc', 'bb'], ['bb', 'xx']
    )
)

array(['aa', 'cc'], dtype='<U2')

## Logical AND (∧)

### Dyadic - Lowest Common Multiple (AND)

In [45]:
#       0 1 0 1 ∧ 0 0 1 1
# 0 0 0 1

np.vectorize(np.lcm)(
    [0, 1, 0, 1], [0, 0, 1, 1]
)

array([0, 0, 0, 1])

In [46]:
#       15 1 2 7 ∧ 35 1 4 0
# 105 1 4 0

np.vectorize(np.lcm)(
    [15, 1, 2, 7], [35, 1, 4, 0]
)

array([105,   1,   4,   0])

## Logical OR (∨)

### Dyadic - Greatest Common Divisor (OR)

In [47]:
#       0 1 0 1 ∨ 0 0 1 1
# 0 1 1 1

np.vectorize(np.gcd)(
    [0, 1, 0, 1], [0, 0, 1, 1]
)

array([0, 1, 1, 1])

In [48]:
#       15 1 2 7 ∨ 35 1 4 0
# 5 1 2 7

np.vectorize(np.gcd)(
    [15, 1, 2, 7], [35, 1, 4, 0]
)

array([5, 1, 2, 7])

## Logical NAND (⍲)

### Dyadic - NAND

In [49]:
#       0 1 0 1 ⍲ 0 0 1 1
# 1 1 1 0

def nand(alpha, omega):
    return int(
        not (alpha and omega)
    )

np.vectorize(nand)(
    [0, 1, 0, 1], [0, 0, 1, 1]
)

array([1, 1, 1, 0])

## Logical NOR (⍱)

### Dyadic - NOR

In [50]:
#       0 1 0 1 ⍱ 0 0 1 1
# 1 0 0 0

def nor(alpha, omega):
    return int(
        not (alpha or omega)
    )

np.vectorize(nor)(
    [0, 1, 0, 1], [0, 0, 1, 1]
)

array([1, 0, 0, 0])

## Less Than (<)

### Dyadic - Less Than

In [51]:
#       1 2 3 < 4 2 ¯1
# 1 0 0

[
    int(val) for val in 
    np.array([1, 2, 3]) < np.array([4, 2, -1])
]

[1, 0, 0]

In [52]:
#       1 2 3 < 2
# 1 0 0

[
    int(val) for val in 
    np.array([1, 2, 3]) < np.array([2])
]

[1, 0, 0]

## Greater Than (>)

### Dyadic - Greater Than

In [53]:
#       1 2 3 > 4 2 ¯1
# 0 0 1

[
    int(val) for val in 
    np.array([1, 2, 3]) > np.array([4, 2, -1])
]

[0, 0, 1]

In [54]:
#       1 2 3 > 2
# 0 0 1

[
    int(val) for val in 
    np.array([1, 2, 3]) > np.array([2])
]

[0, 0, 1]

## Less Than Or Equal To (≤)

### Dyadic - Less Than or Equal To

In [55]:
#       1 2 3 ≤ 4 2 ¯1
# 1 1 0

[
    int(val) for val in 
    np.array([1, 2, 3]) <= np.array([4, 2, -1])
]

[1, 1, 0]

In [56]:
#       1 2 3 ≤ 2
# 1 1 0

[
    int(val) for val in 
    np.array([1, 2, 3]) <= np.array([2])
]

[1, 1, 0]

## Greater Than Or Equal To (≥)

### Dyadic - Greater Than Or Equal To

In [57]:
#       1 2 3 ≥ 4 2 ¯1
# 0 1 1

[
    int(val) for val in 
    np.array([1, 2, 3]) >= np.array([4, 2, -1])
]

[0, 1, 1]

In [58]:
#       1 2 3 ≥ 2
# 0 1 1

[
    int(val) for val in 
    np.array([1, 2, 3]) >= np.array([2])
]

[0, 1, 1]

## Equal (=)

### Dyadic - Equal To

In [59]:
#       1 2 3 = 4 2 ¯1
# 0 1 0

[
    int(val) for val in 
    np.array([1, 2, 3]) == np.array([4, 2, -1])
]

[0, 1, 0]

In [60]:
#       0 1 0 1 = 0 0 1 1
# 1 0 0 1

[
    int(val) for val in 
    np.array([0, 1, 0, 1]) == np.array([0, 0, 1, 1])
]

[1, 0, 0, 1]

In [61]:
#       'Banana' = 'a'
# 0 1 0 1 0 1

def equal_to(alpha, omega):
    return np.array(
        [int(a == omega) for a in alpha]
    )

equal_to(
    'Banana', 'a'
)

array([0, 1, 0, 1, 0, 1])

In [62]:
#       7 = '7'
# 0

int(7 == '7')

0

## Not Equal (≠)

### Monadic - Unique Mask

In [63]:
#       ≠ 'Banana'
# 1 1 1 0 0 0

def unique_mask(omega):
    li = [char for char in omega]
    uniq = np.unique(li, return_index=True)
    uniq_idx = uniq[1]
    return np.array(
        [int(i in uniq_idx) for i in range(len(omega))]
    )

unique_mask('Banana')

array([1, 1, 1, 0, 0, 0])

In [64]:
#       ≠ 'Mississippi'
# 1 1 1 0 0 0 0 0 1 0 0

unique_mask('Mississippi')

array([1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0])

### Dyadic - Not Equal To

In [65]:
#       1 2 3 ≠ 4 2 ¯1
# 1 0 1

[
    int(val) for val in 
    np.array([1, 2, 3]) != np.array([4, 2, -1])
]

[1, 0, 1]

In [66]:
#       0 1 0 1 ≠ 0 0 1 1
# 0 1 1 0

[
    int(val) for val in 
    np.array([0, 1, 0, 1]) != np.array([0, 0, 1, 1])
]

[0, 1, 1, 0]

In [67]:
#       'Banana' ≠ 'a'
# 1 0 1 0 1 0

def not_equal_to(alpha, omega):
    return np.array(
        [int(a != omega) for a in alpha]
    )

not_equal_to(
    'Banana', 'a'
)

array([1, 0, 1, 0, 1, 0])

In [68]:
#       7 ≠ '7'
# 1

int(7 != '7')

1

## Equal Underbar (≡)

### Monadic - Depth

In [69]:
#       ≡ 7
# 0

print("Not Implemented Yet")

Not Implemented Yet


In [70]:
#       ≡ 'abc'
# 1

print("Not Implemented Yet")

Not Implemented Yet


In [71]:
#       ≡ (1 2)(3 4)
# 2

print("Not Implemented Yet")

Not Implemented Yet


In [72]:
#       ≡ (1 2)(3 4)5
# ¯2

print("Not Implemented Yet")

Not Implemented Yet


### Dyadic - Match

In [73]:
#       'b' 'e' 'x' ≡ 'bex'
# 1

def match(alpha, omega):
    if len(alpha) != len(omega):
        return 0
    else:
        result = [
            alpha[i] == omega[i] 
            for i in range(len(alpha))
        ]
    return int(all(result))

match(['b', 'e', 'x'], 'bex')

1

In [74]:
#       1 ≡ 1 1
# 0

match([1], [1, 1])

0

## Equal Underbar Slash (≢)

### Monadic - Tally

In [75]:
#       ≢ 'a'
# 1



In [76]:
#       ≢ 7 4 2
# 3



In [77]:
#       ≢ 5 4 3⍴0 
# 5



In [78]:
#       ≢ (1 2)(3 4)
# 2



In [79]:
#      mat
# 1 2 3
# 4 5 6
#       ≢ mat   ⍝ note how \

# 2
#       ⍴ mat   ⍝ differs from \

# 2 3



### Dyadic - Not Match

In [80]:
#       'bex' ≢ 'b','e','x' 
# 0

def not_match(alpha, omega):
    if len(alpha) != len(omega):
        return 1
    else:
        result = [
            alpha[i] != omega[i] 
            for i in range(len(alpha))
        ]
    return int(all(result))

not_match('bex', ['b', 'e', 'x'])

0

In [81]:
#       1 ≢ 1 1
# 1


not_match([1], [1, 1])

1

--------------------------------
## Structural
--------------------------------

## Rho (⍴)

### Monadic - Shape

In [82]:
#       mat
# 1  2  3  4
# 5  6  7  8
# 9 10 11 12

#       ⍴ mat
# 3 4

mat = np.matrix('1 2 3 4;5 6 7 8;9 10 11 12')
mat.shape

(3, 4)

In [83]:
#       ⍴⍴ mat
# 2

len(mat.shape)

2

In [84]:
#       ⍴ 'your boat'
# 9

len('your boat')

9

In [85]:
#       ⍴ 7
#

np.array(7).shape

()

In [86]:
#       ⍴⍴ 7
# 0

len(np.array(7).shape)

0

### Dyadic - Reshape

In [87]:
#       2 3 4 ⍴ 1 2 3 4 5 6 7
# 1 2 3 4
# 5 6 7 1
# 2 3 4 5

# 6 7 1 2
# 3 4 5 6
# 7 1 2 3



## Comma (,)

### Monadic - Ravel

In [88]:
#       cube    ⍝ 3D array
# 1 2
# 3 4

# 5 6
# 7 8
#       , cube
# 1 2 3 4 5 6 7 8



In [89]:
#       ,[2 3] cube    ⍝ Ravel with axes
# 1 2 3 4
# 5 6 7 8



### Dyadic - Catenate/Laminate (Join)

In [90]:
#       1 2 3 , 4 5 6
# 1 2 3 4 5 6



In [91]:
#       cube , 99
# 1 2 99
# 3 4 99

# 5 6 99
# 7 8 99



In [92]:
#       1 2 3 ,[0.5] 4 5 6   ⍝ Laminate
# 1 2 3
# 4 5 6 



## Comma Bar (⍪)

### Monadic - Table

In [93]:
#       ⍪ 2 3 4
# 2
# 3
# 4



In [94]:
#       cube    ⍝ 3D array
# 1 2
# 3 4

# 5 6
# 7 8
#       ⍪ cube
# 1 2 3 4
# 5 6 7 8



### Dyadic - Catenate First/Laminate

In [95]:
#       mat
# 1 2 3
# 4 5 6

#       mat ⍪ 0
# 1 2 3
# 4 5 6
# 0 0 0



In [96]:
#       mat ⍪ 7 8 9
# 1 2 3
# 4 5 6
# 7 8 9



## Circle Stile (⌽)

### Monadic - Reverse

In [97]:
#       ⌽ 'trams'
# smart

'trams'[::-1]

'smart'

In [98]:
#       mat
# 1  2  3  4
# 5  6  7  8
# 9 10 11 12

#       ⌽ mat
#  4  3  2 1
#  8  7  6 5
# 12 11 10 9


mat = np.matrix('1 2 3 4;5 6 7 8;9 10 11 12')


In [99]:
#       ⌽[1] mat
# 9 10 11 12
# 5  6  7  8
# 1  2  3  4

mat[::-1]

matrix([[ 9, 10, 11, 12],
        [ 5,  6,  7,  8],
        [ 1,  2,  3,  4]])

### Dyadic - Rotate

In [100]:
#       3 ⌽ 'HatStand'
# StandHat



In [101]:
#       ¯2 ⌽ 1 2 3 4 5 6
# 5 6 1 2 3 4



In [102]:
#       ¯1 ⌽ mat
#  4 1  2  3
#  8 5  6  7
# 12 9 10 11



In [103]:
#       1 ¯1 2 ⌽ mat
#  2  3 4  1
#  8  5 6  7
# 11 12 9 10



In [104]:
#       0 1 2 ¯1 ⌽[1] mat
# 1  6 11 12
# 5 10  3  4
# 9  2  7  8



## Circle Bar (⊖)

### Monadic - Reverse First

In [105]:
#       mat
# 1  2  3  4
# 5  6  7  8
# 9 10 11 12

#       ⊖ mat
# 9 10 11 12
# 5  6  7  8
# 1  2  3  4

mat = np.matrix('1 2 3 4;5 6 7 8;9 10 11 12')
mat[::-1]

matrix([[ 9, 10, 11, 12],
        [ 5,  6,  7,  8],
        [ 1,  2,  3,  4]])

### Dyadic - Rotate First

In [106]:
#       0 1 2 ¯1 ⊖ mat
# 1  6 11 12
# 5 10  3  4
# 9  2  7  8



## Transpose (⍉)

### Monadic - Transpose

In [107]:
#       mat
# 1 2 3
# 4 5 6

#       ⍉ mat
# 1 4
# 2 5
# 3 6

mat = np.matrix('1 2 3; 4 5 6')
mat.T

matrix([[1, 4],
        [2, 5],
        [3, 6]])

### Dyadic - Dyadic Transpose

In [108]:
#       2 1 ⍉ mat
# 1 4
# 2 5
# 3 6



In [109]:
#       1 1 ⍉ mat   ⍝ leading diagonal
# 1 5



## Up Arrow (↑)

### Monadic - Mix

In [110]:
#       ↑ 'Hip' 'Hop'
# Hip
# Hop

np.array(['Hip', 'Hop'])

array(['Hip', 'Hop'], dtype='<U3')

In [111]:
#       ↑ (6 4) 5 3
# 6 4
# 5 0
# 3 0



In [112]:
#       ↑[0.5] 'Hip' 'Hop'
# HH
# io
# pp



### Dyadic - Take

In [113]:
#       4 ↑ 'Pineapple'
# Pine

'Pineapple'[:4]

'Pine'

In [114]:
#       ¯5 ↑ 'Pineapple'
# apple

'Pineapple'[-5:]

'apple'

In [115]:
#       mat
# 1  2  3  4
# 5  6  7  8
# 9 10 11 12

#       2 ¯3 ↑ mat
# 2 3 4
# 6 7 8



In [116]:
#       ¯2 ↑ mat
# 5  6  7  8
# 9 10 11 12



In [117]:
#       ¯2 3 ↑ 7
# 0 0 0
# 7 0 0



## Down Arrow (↓)

### Monadic - Split

In [118]:
#       mat
# 1  2  3  4
# 5  6  7  8
# 9 10 11 12

#       ↓ mat
# ┌───────┬───────┬──────────┐
# │1 2 3 4│5 6 7 8│9 10 11 12│
# └───────┴───────┴──────────┘



In [119]:
#       ↓[1] mat
# ┌─────┬──────┬──────┬──────┐
# │1 5 9│2 6 10│3 7 11│4 8 12│
# └─────┴──────┴──────┴──────┘



### Dyadic - Drop

In [120]:
#       4 ↓ 'Pineapple'
# apple

'Pineapple'[4:]

'apple'

In [121]:
#       ¯5 ↓ 'Pineapple'
# Pine


'Pineapple'[:-5]

'Pine'

In [122]:
#       1 ¯2 ↓ mat
# 5  6
# 9 10



In [123]:
#       1 ↓ mat
# 5  6  7  8
# 9 10 11 12



## Left Shoe (⊂)

### Monadic - Enclose

In [124]:
#       1(2 3)
# ┌─┬───┐
# │1│2 3│
# └─┴───┘
#       ⊂ 1(2 3)
# ┌───────┐
# │┌─┬───┐│
# ││1│2 3││
# │└─┴───┘│
# └───────┘



In [125]:
#       ⊂⊂ 1(2 3)
# ┌─────────┐
# │┌───────┐│
# ││┌─┬───┐││
# │││1│2 3│││
# ││└─┴───┘││
# │└───────┘│
# └─────────┘



### Dyadic - Partitioned Enclose

In [126]:
#        0 1 0 1 ⊂ 1 2 3 4
# ┌───┬─┐
# │2 3│4│
# └───┴─┘



## Left Shoe Underbar (⊆)

### Monadic - Nest

In [127]:

#       ⊆ 'this'
# ┌────┐
# │this│
# └────┘



In [128]:
#       ⊆ 'this' 'that'
# ┌────┬────┐
# │this│that│
# └────┴────┘



### Dyadic - Partition

In [129]:
#       1 0 0 1 1 ⊆ 1 2 3 4 5
# ┌─┬───┐
# │1│4 5│
# └─┴───┘



In [130]:
#        1 1 2 2 2⊆⍳5
# ┌───┬─────┐
# │1 2│3 4 5│
# └───┴─────┘



In [131]:
#     ' ' (≠⊆⊢) ' many a  time'
# ┌────┬─┬────┐
# │many│a│time│
# └────┴─┴────┘



## Epsilon (∊)

### Monadic - Enlist

In [132]:
#       mat
# 1 2 3
# 4 5 6
#       ∊ 0 mat (7 8) 9
# 0 1 2 3 4 5 6 7 8 9



In [133]:
#       ∊ 2 3⍴1 'abc'
# 1 abc 1 abc 1 abc



### Dyadic - Membership

In [134]:
#       'abc' 4 ∊ 4 'ab' 'abcd'
# 0 1

def membership(alpha, omega):
    result = []
    for a in alpha:
        result.append(
            int(a in omega)
        )
    return np.array(result)

membership(['abc', 4], [4, 'ab', 'abcd'])

array([0, 1])

In [135]:
#       mat ∊ 6 2 7 4
# 0 1 0
# 1 0 1



--------------------------------------------
## Selection and Set Operations
--------------------------------------------

## Squad (⌷)

### Monadic - Materialise

In [136]:
#       ⌷ ⍵
# If ⍵ is an array, returns ⍵.
# If ⍵ is ref to an instance of a Class with a 
# Numbered Default property, all items of that property
# are returned.
# If ⍵ is a collection, returns all elements
# in the collection as an array.



### Dyadic - Index

In [137]:
#       mat
# 1  2  3  4
# 5  6  7  8
# 9 10 11 12

#       2 3 ⌷ mat
# 7



In [138]:
#       2 ⌷ mat
# 5 6 7 8



In [139]:
#       2 ⌷[2] mat
# 2 6 10



## Right Shoe (⊃)

### Monadic - First

In [140]:
#       ⊃ 'Word'
# W

"Word"[0]

'W'

In [141]:
#       ⊃ (1 2)(3 4 5)
# 1 2



### Dyadic - Pick

In [142]:
#       3 ⊃ 'Word'
# r

"Word"[2]  # APL defaults to base-1

'r'

In [143]:
#       2 ⊃ (1 2)(3 4 5)
# 3 4 5



In [144]:
#       2 1 ⊃ (1 2)(3 4 5)
# 3



## Slash (/)

### Monadic - Replicate

In [145]:
#       3 1 ¯2 2 / 6 7 8 9
# 6 6 6 7 0 0 9 9

def replicate(alpha, omega):
    assert len(alpha) == len(omega)
    
    
    result = []
    count = -1
    for a in alpha:
        count += 1
        if a < 0:
            for i in range(abs(a)):
                result.append(0)
        for i in range(a):
            result.append(omega[count])
                
    return np.array(
        result
    )

replicate([3, 1, -2, 2], [6, 7, 8, 9])

array([6, 6, 6, 7, 0, 0, 9, 9])

In [146]:
#       1 0 1 0 1 / 'Heart'
# Hat

def mask(alpha, omega):
    idx = [i for i in range(len(alpha)) if alpha[i] == 1]
    result = [omega[i] for i in range(len(omega)) if i in idx]
    
    if isinstance(omega, str):
        result = "".join(result)
    return result

mask([1, 0, 1, 0, 1], "Heart")

'Hat'

### Dyadic - Reduce (Fold, N-Wise Reduce)

In [147]:
#       +/ 1 2 3 4 5
# 15

np.array([1, 2, 3, 4, 5]).sum()

15

In [148]:
#       2 +/ 1 2 3 4 5   ⍝ pair-wise sum
# 3 5 7 9



In [149]:
#       cube    ⍝ 3D array
#  1  2  3  4
#  5  6  7  8
#  9 10 11 12

# 13 14 15 16
# 17 18 19 20
# 21 22 23 24

#       +/ cube
# 10 26 42
# 58 74 90



In [150]:
#       +/[1] cube    ⍝ sum of planes
# 14 16 18 20
# 22 24 26 28
# 30 32 34 36



In [151]:
#       +/[2] cube    ⍝ column sums
# 15 18 21 24
# 51 54 57 60



## Slash Bar (⌿)

### Monadic - Reduce First

In [152]:
#       mat
# 1  2  3  4
# 5  6  7  8
# 9 10 11 12

#       +⌿ mat
# 15 18 21 24

In [153]:
#       2 +⌿ mat     ⍝ pair-wise
#  6  8 10 12
# 14 16 18 20



### Dyadic - Replicate First (Compress First)

In [154]:
#       1 0 2 ⌿ mat
# 1  2  3  4
# 9 10 11 12
# 9 10 11 12



## Backslash (\)

### Monadic - Scan

In [155]:
#       +\ 1 2 3 4 5
# 1 3 6 10 15

np.array([1, 2, 3, 4, 5]).cumsum()

array([ 1,  3,  6, 10, 15])

In [156]:
#       mat
# 1  2  3  4
# 5  6  7  8
# 9 10 11 12

#       +\ mat
# 1  3  6 10
# 5 11 18 26
# 9 19 30 42



In [157]:
#       +\[1] mat
#  1  2  3  4
#  6  8 10 12
# 15 18 21 24



### Dyadic - Expand

In [158]:
#       3 ¯2 4 \ 7 8
# 7 7 7 0 0 8 8 8 8



In [159]:
#       1 0 1 0 1 \ 'Hat'
# H a t



## Backslash Bar (⍀)

### Monadic - Scan First

In [160]:
#       mat
# 1  2  3  4
# 5  6  7  8
# 9 10 11 12
#
#       +⍀ mat
#  1  2  3  4
#  6  8 10 12
# 15 18 21 24 



### Dyadic - Expand First

In [161]:
#       1 0 2 1 ⍀ mat
# 1  2  3  4
# 0  0  0  0
# 5  6  7  8
# 5  6  7  8
# 9 10 11 12



## Down Shoe (∪)

### Monadic - Unique

In [162]:
#       ∪ 'ab' 'ba' 'ab' 1 1 2
# ┌──┬──┬─┬─┐
# │ab│ba│1│2│
# └──┴──┴─┴─┘

np.unique(['ab', 'ba', 'ab', 1, 1, 2])

array(['1', '2', 'ab', 'ba'], dtype='<U2')

In [163]:
#       mat
# flywheel
# shyster 
# flywheel
#      ∪mat
# flywheel
# shyster 



### Dyadic - Union

In [164]:
#       'ab' 'cde' 'fg' ∪ 'a' 'ab'
# ┌──┬───┬──┬─┐
# │ab│cde│fg│a│
# └──┴───┴──┴─┘



## Up Shoe (∩)

### Dyadic - Intersection

In [165]:
#       22 'ab' 'fg' ∩ 'a' 'ab' 22
# ┌──┬──┐
# │22│ab│
# └──┴──┘



## Left Tack (⊣)

### Monadic - Same

In [166]:
#       ⊣  1 2 3
# 1 2 3

def same(omega):
    return omega

same(
    np.array([1, 2, 3])
)

array([1, 2, 3])

### Dyadic - Left

In [167]:
#       'L' ⊣ 'R'
# L

def left(alpha, omega):
    return alpha

left('L', 'R')

'L'

In [168]:
#       ⊣/ 1 2 3
# 1

[1, 2, 3][0]

1

## Right Tack (⊢)

### Monadic - Same

In [169]:
#       ⊢  1 2 3
# 1 2 3

same(
    np.array([1, 2, 3])
)

array([1, 2, 3])

### Dyadic - Right

In [170]:
#       'L' ⊢ 'R'
# R

def right(alpha, omega):
    return omega

right('L', 'R')

'R'

In [171]:
#       ⊢/ 1 2 3
# 3

[1, 2, 3][-1]

3

----------------------
## Search and Ordering
----------------------

## Iota (⍳)

### Monadic - Index Generator

In [172]:
#       ⍳ 10
# 1 2 3 4 5 6 7 8 9 10

def index(omega):
    return np.array(   
        [i for i in range(1, omega + 1)]
    )

index(10)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [173]:
#       ⍳ 2 3
# ┌───┬───┬───┐
# │1 1│1 2│1 3│
# ├───┼───┼───┤
# │2 1│2 2│2 3│
# └───┴───┴───┘



### Dyadic - Index Of

In [174]:
#       'ABCDABCDEF' ⍳ 'ACF'
# 1 3 10

def index_of(alpha, omega, base_1 = False):
    result = []
    
    for o in omega:
        result.append(alpha.index(o))
    
    if base_1:
        result = [i + 1 for i in result]
        
    return result

index_of('ABCDABCDEF', 'ACF', base_1 = True)

[1, 3, 10]

In [175]:
#       mat
# 1 2
# 3 4
# 5 6
#       mat ⍳ 5 6
# 3



## Iota Underbar (⍸)

### Monadic - Where

In [176]:
#       ⍸ 1 0 0 1 1
# 1 4 5



In [177]:
#       bmat
# 0 1 0
# 1 0 1
#       ⍸ bmat
# ┌───┬───┬───┐
# │1 2│2 1│2 3│
# └───┴───┴───┘



### Dyadic - Interval Index

In [178]:
#       'AEIOU' ⍸ 'DYALOG'
# 1 5 1 3 4 2



In [179]:
#       2 4 6 ⍸ 1 2 3 4 5 6 7
# 0 1 1 2 2 3 3



In [180]:
#       mat
# 1 2
# 3 4
# 5 6
#       mat ⍸ 3 3
# 1



In [181]:
#       mat ⍸ 3 5
# 2



## Epsilon Underbar (⍷)

### Dyadic - Find

In [182]:
#       'ana' ⍷ 'Banana'
# 0 1 0 1 0 0

def find(alpha, omega):
    result = []
    len_alpha = len(alpha)
    for i in range(len(omega)):
        try:
            if omega[i:i + len_alpha] == alpha:
                result.append(1)
            else:
                result.append(0)
        except:
            result.append(0)
    return result

find('ana', 'Banana')

[0, 1, 0, 1, 0, 0]

In [183]:
#       X Y
# ┌───┬───────┐
# │0 1│0 1 0 0│
# │1 0│1 0 0 1│
# │   │0 0 1 0│
# │   │0 1 0 0│
# └───┴───────┘

#       X ⍷ Y
# 1 0 0 0
# 0 0 1 0
# 0 1 0 0
# 0 0 0 0



## Grade Up (⍋)

### Monadic - Grade Up

In [184]:
# Indices which would select items in ascending order.
#
#       ⍋ 33 11 44 66 22
# 2 5 1 3 4



In [185]:
#       names←'Joe' 'Sue' 'Sam'
#       ages←34 22 25
#
#       names[⍋ages]
# ┌───┬───┬───┐
# │Sue│Sam│Joe│
# └───┴───┴───┘



In [186]:
#       ⍋ 'ABC' ⎕NULL ⍬ ¯3j4 'A'
# 3 2 4 5 1



### Dyadic - Dyadic Grade Up

In [187]:
# Provide collating sequence for character data.
#
#       ⍋ 'Banana'
# 1 2 4 6 3 5



In [188]:
#       'an' ⍋ 'Banana'
# 2 4 6 3 5 1



## Grade Down (⍒)

### Monadic - Grade Down

In [189]:
# Indices which would select items in descending order.
#
#       ⍒ 33 11 44 66 22
# 4 3 1 5 2



In [190]:
#       names←'Joe' 'Sue' 'Sam'
#       ages←34 22 25
#
#       names[⍒ages]
# ┌───┬───┬───┐
# │Joe│Sam│Sue│
# └───┴───┴───┘ 



### Dyadic - Dyadic Grade Down

In [191]:
# Provide collating sequence for character data.

#       ⍒ 'Banana'
# 3 5 2 4 6 1



In [192]:
#       'an' ⍒ 'Banana'
# 1 3 5 2 4 6



-----------------------------------
## Operators
-----------------------------------

## Diaeresis (¨)

### Monadic - Each (Map)

In [193]:
#       ⊃¨ 1 2 3 'ABC' (9 8 7)
# 1 2 3 A 9



In [194]:
#       +/¨ (1 2 3 4)(5 6 7)
# 10 18



In [195]:
#       3 ↑¨ 1 2 (3 4) 'V'
# ┌─────┬─────┬─────┬───┐
# │1 0 0│2 0 0│3 4 0│V  │
# └─────┴─────┴─────┴───┘



In [196]:
#       1 2 3 ,¨ 99
# ┌────┬────┬────┐
# │1 99│2 99│3 99│
# └────┴────┴────┘



## Tilde Diaeresis (⍨)

### Monadic - After a function  = Commute (Switch)

In [197]:
#       2 ⍴ 3     ⍝ ⍺ ⍴ ⍵
# 3 3



In [198]:
#       2 ⍴⍨ 3    ⍝ ⍵ ⍴ ⍺
# 2 2 2



In [199]:
#       ⍴⍨ 3      ⍝ ⍵ ⍴ ⍵
# 3 3 3

 

### Monadic - After some data = Constant

In [200]:
#       'mu'⍨ 'any' ⎕NULL   ⍝ Always returns its operand
# mu



In [201]:
#       1E100 ('mu'⍨) 1j1
# mu



In [202]:
#       ¯1⍨¨ ⍳2 3
# ¯1 ¯1 ¯1
# ¯1 ¯1 ¯1



## Star Diaeresis (⍣)

### Dyadic - Power

In [203]:
#       cube    ⍝ 3D array
# AB
# CD

# EF
# GH
#       (↓⍣1) cube   ⍝ split once
# ┌──┬──┐
# │AB│CD│
# ├──┼──┤
# │EF│GH│
# └──┴──┘



In [204]:
#       (↓⍣2) cube   ⍝ split twice
# ┌───────┬───────┐
# │┌──┬──┐│┌──┬──┐│
# ││AB│CD│││EF│GH││
# │└──┴──┘│└──┴──┘│
# └───────┴───────┘



In [205]:
#       f ← (32∘+)∘(×∘1.8)   ⍝ Fahrenheit from Celsius

#       f ¯273 ¯40 0 100     ⍝ Fahrenheit
# ¯459.4 ¯40 32 212



In [206]:
#       c ← f⍣¯1             ⍝ Inverse: Celsius from Fahrenheit

#       c ¯459.4 ¯40 32 212  ⍝ Celsius
# ¯273 ¯40 0 100



In [207]:
#       1 +∘÷⍣= 1            ⍝ fixpoint: golden mean
# 1.61803



## Dot (.)

### Dyadic - Product

In [208]:
# Inner Product f.g      

#       1 2 3 +.× 4 5 6
# 32

np.dot(
    [1, 2, 3], [4, 5, 6]
)

32

In [209]:
#       3 ∧.= 3 3 3 3
# 1



In [210]:
#       mat
# 1 2
# 3 4
#       mat +.× mat   ⍝ matrix product
#  7 10
# 15 22



In [211]:
# Outer Product ∘.g

#       1 2 3 ∘.× 4 5 6 7
#  4  5  6  7
#  8 10 12 14
# 12 15 18 21

np.outer(
    [1, 2, 3], [4, 5, 6, 7]
)

array([[ 4,  5,  6,  7],
       [ 8, 10, 12, 14],
       [12, 15, 18, 21]])

## Jot (∘)

### Dyadic - Beside and Bind

In [212]:
# NB: ∘ is also used in outer product ∘.f - see Dot (.)

# Beside

#       ⌽∘⍳¨ 3 4 5
# ┌─────┬───────┬─────────┐
# │3 2 1│4 3 2 1│5 4 3 2 1│
# └─────┴───────┴─────────┘



In [213]:
#       ¯1 ⌽∘⍳¨ 3 4 5
# ┌─────┬───────┬─────────┐
# │3 1 2│4 1 2 3│5 1 2 3 4│
# └─────┴───────┴─────────┘



In [214]:
#       +∘÷/ 40⍴1    ⍝ continued fraction
# 1.61803



## Quad Equal (⌸)

### Monadic - Key

In [215]:
#       'Banana' {⍺ ⍵}⌸ 3 1 4 1 5 9
# ┌─┬─────┐
# │B│3    │
# ├─┼─────┤
# │a│1 1 9│
# ├─┼─────┤
# │n│4 5  │
# └─┴─────┘

from collections import defaultdict

def key(alpha, omega):
    assert len(alpha) == len(omega)
    items = [i for i in zip(alpha, omega)]
    result = defaultdict(list)
    
    for i in items:
        a = i[0]
        o = i[1]
        result[a].append(o)
    
    return result

key("Banana", [3, 1, 4, 1, 5, 9])

defaultdict(list, {'B': [3], 'a': [1, 1, 9], 'n': [4, 5]})

In [216]:
#       'Banana' {⍺,+/⍵}⌸ 3 1 4 1 5 9
# B  3
# a 11
# n  9 



In [217]:
#       'Banana' {⍺ ⍵}⌸ 1 2 3 4 5 6
# ┌─┬─────┐
# │B│1    │
# ├─┼─────┤
# │a│2 4 6│
# ├─┼─────┤
# │n│3 5  │
# └─┴─────┘



In [218]:
#       {⍺ ⍵}⌸ 'Banana'  ⍝ (same as above)
# ┌─┬─────┐
# │B│1    │
# ├─┼─────┤
# │a│2 4 6│
# ├─┼─────┤
# │n│3 5  │
# └─┴─────┘



## Jot Diaeresis (⍤)

### Dyadic - (f⍤g): Atop

In [219]:
#       -⍤÷ 4      ⍝ (  f⍤g y) ≡  f   g y
# ¯0.25



In [220]:
#       12 -⍤÷ 4   ⍝ (x f⍤g y) ≡ (f x g y)
# ¯3



In [221]:
#       3 1 4 1 5 ~⍤∊ 1 2 3
# 0 0 1 0 1



### Dyadic - (f⍤a):   Rank 

In [222]:
#       cube    ⍝ 3D array
#  1  2  3
#  4  5  6

#  7  8  9
# 10 11 12

#       (,⍤2) cube
# 1 2 3  4  5  6
# 7 8 9 10 11 12



In [223]:
#       cmat    ⍝ character matrix
# abc
# zxy 



In [224]:
#       (⍋⍤1) cmat    ⍝ grade-up by row  
# 1 2 3 
# 2 3 1



In [225]:
#       nmat     ⍝ numeric matrix
# 1  2  3  4
# 5  6  7  8
# 9 10 11 12

#       10 20 30 (+⍤0 1) nmat  ⍝ scalars plus vectors
# 11 12 13 14 
# 25 26 27 28 
# 39 40 41 42



## Circle Dieresis (⍥)

### Dyadic - Over

In [226]:
#       -⍥⌊ 3.6                 ⍝ Same as ∘ or ⍤ monadically
# ¯3



In [227]:
#       5.1 -⍥⌊ 3.6             ⍝ Applies ⌊ to both arguments
# 2



In [228]:
#       'Dyalog' ≡⍥⎕C 'DYALOG'  ⍝ Case-insensitive match
# 1



In [229]:
#       'Dyalog' ≡⍥⎕C 'IBM'
# 0



## Quad Diamond (⌺)

### Dyadic - Stencil

In [230]:
#       mat
#  1  2  3  4
#  5  6  7  8
#  9 10 11 12
# 13 14 15 16

#       ({⊂⍵}⌺3 3) mat
# ┌───────┬────────┬────────┬───────┐
# │0 0 0  │0 0 0   │0 0 0   │0 0 0  │
# │0 1 2  │1 2 3   │2 3 4   │3 4 0  │
# │0 5 6  │5 6 7   │6 7 8   │7 8 0  │
# ├───────┼────────┼────────┼───────┤
# │0 1  2 │1  2  3 │ 2  3  4│ 3  4 0│
# │0 5  6 │5  6  7 │ 6  7  8│ 7  8 0│
# │0 9 10 │9 10 11 │10 11 12│11 12 0│
# ├───────┼────────┼────────┼───────┤
# │0  5  6│ 5  6  7│ 6  7  8│ 7  8 0│
# │0  9 10│ 9 10 11│10 11 12│11 12 0│
# │0 13 14│13 14 15│14 15 16│15 16 0│
# ├───────┼────────┼────────┼───────┤
# │0  9 10│ 9 10 11│10 11 12│11 12 0│
# │0 13 14│13 14 15│14 15 16│15 16 0│
# │0  0  0│ 0  0  0│ 0  0  0│ 0  0 0│
# └───────┴────────┴────────┴───────┘



In [231]:
#       ({+/,⍵}⌺3 3) mat
# 14 24 30 22
# 33 54 63 45
# 57 90 99 69
# 46 72 78 54



## At (@)

### Dyadic - At

In [232]:
#       (0@2 4) 1 2 3 4 5
# 1 0 3 0 5



In [233]:
#       10 (×@2 4) 1 2 3 4 5
# 1 20 3 40 5



In [234]:
#       (÷@2 4) 1 2 3 4 5
# 1 0.5 3 0.25 5



In [235]:
#       '*'@(2∘|) 1 2 3 4 5   ⍝ Boolean selection 1 0 1 0 1
# * 2 * 4 *



In [236]:
#       ⌽@(2∘|) 1 2 3 4 5     ⍝ Reversal of sub-array 1 3 5
# 5 2 3 4 1



## Quad Colon (⍠)

### Dyadic - Variant

In [237]:
#       ('a' ⎕R 'x') 'ABC'           ⍝ 'a' replaced with 'x'
# ABC



In [238]:
#       ('a' ⎕R 'x' ⍠ 'IC' 1) 'ABC'  ⍝ .. Ignoring Case
# xBC



In [239]:
#       IgnCase ← ⍠ 'IC' 1

#       'a' ⎕R 'x' IgnCase 'ABC'
# xBC 



------------------------------
## Miscellaneous
------------------------------

## High Minus (¯)

In [240]:
# Qualifier for negative number

#       1 + ¯1 0 1 ¯3
# 0 1 2 ¯2



In [241]:
#       3e¯2
# 0.03



## Left Arrow (←)

### Assignment - Naming

In [242]:
# V ← 5 6 7



In [243]:
# (i(j k)) ← 4(5 6)



In [244]:
# sum ← +⌿



In [245]:
# product ← {×/⍵}



In [246]:
# inverse ← ⍣¯1



### Assignment - Modification

In [247]:
# V +← 1



In [248]:
# V[2] ← 0



In [249]:
# (⊃V) ← 2



## Zilde (⍬)

### Niladic:  Empty Numeric Vector

In [250]:
#       ⍬≡⍳0
# 1



In [251]:
#       ⍬≡0⍴0
# 1



In [252]:
#       ⍬≡0 0⍴0
# 0



In [253]:
#       ⍬≡''
# 0



## Hydrant (⍎)

### Monadic - Execute

In [254]:
#       ⍎ '1+1'
# 2

exec('print(1+1)')

2


In [255]:
#       V ← 1 2 3
#       ⍎ 'V'
# 1 2 3 

V = [1, 2, 3]
exec('print(V)')

[1, 2, 3]


## Thorn (⍕)

### Monadic - Format

In [256]:
# NB: In the following examples space characters
#     are represented by small dots: ···

#       4 5 6          ⍝ numeric vector
# 4 5 6
#       ⍕ 4 5 6        ⍝ equivalent character vector
# 4·5·6



In [257]:
#       mat            ⍝ numeric matrix
# 1 2 3
# 4 5 6

#       ⍕ mat          ⍝ equivalent character matrix
# 1·2·3
# 4·5·6



### Dyadic - Format By Specification

In [258]:
# Field-width and number of decimal places:

#       6 2 ⍕ 3.125 0.002
# ··3.13··0.00



In [259]:
#       6 2 ⍕ mat
# ··1.00··2.00··3.00
# ··4.00··5.00··6.00



In [260]:
#       6 2 ⍕ 1234   ⍝ (field not wide enough)
# ******



## Diamond (⋄)

### Syntax:    Statement Separator

In [261]:
#       Statements are evaluated sequentially
#       from left to right.

#       A←4 ⋄ A←A×3 ⋄ A÷2
# 6



## Lamp (⍝)

### Syntax: Comment

In [262]:
# Text to the right of ⍝ is ignored.

#       2+3  ⍝ this is a comment
# 5



## Del (∇)

In [263]:
# Del Syntax:         dfn self-reference (recursion)

#       fact←{             ⍝ Factorial ⍵.
# 	      ⍵≤1: 1         ⍝ small ⍵: finished
# 	      ⍵×∇ ⍵-1        ⍝ otherwise: recurse
# 	  }



In [264]:
# Double-Del Syntax:  dop self-reference

#     pow←{                ⍝ power operator: apply ⍵⍵ times
# 	    ⍵⍵=0:⍵           ⍝ ⍵⍵ is 0: finished
# 	    ⍺⍺ ∇∇(⍵⍵-1)⍺⍺ ⍵  ⍝ otherwise: recurse
# 	}



## Alpha (⍺)

### Alpha Syntax:           Left argument of a dfn

In [265]:
#       2 {⍺+1} 5
# 3



### Double-Alpha Syntax:    Left Operand of a dop

In [266]:
#       3 +{⍺ ⍺⍺ ⍵} 4
# 7



## Omega (⍵)

### Omega Syntax:           Right argument of a dfn

In [267]:
#       2 {⍵+1} 5
# 6



### Double-Omega Syntax:    Right operand of a dop

In [268]:
#       3 +{⍺ ⍵⍵ ⍵}× 4
# 12

